# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qspectrumanalyzer_smoothing_frequency.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QSpectrumAnalyzerSmoothingFrequency(object):
    def setupUi(self, QSpectrumAnalyzerSmoothingFrequency):
        QSpectrumAnalyzerSmoothingFrequency.setObjectName("QSpectrumAnalyzerSmoothingFrequency")
        QSpectrumAnalyzerSmoothingFrequency.resize(250, 130)
        self.verticalLayout = QtWidgets.QVBoxLayout(QSpectrumAnalyzerSmoothingFrequency)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(QSpectrumAnalyzerSmoothingFrequency)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.windowFunctionComboBox = QtWidgets.QComboBox(QSpectrumAnalyzerSmoothingFrequency)
        self.windowFunctionComboBox.setObjectName("windowFunctionComboBox")
        self.windowFunctionComboBox.addItem("")
        self.windowFunctionComboBox.addItem("")
        self.windowFunctionComboBox.addItem("")
        self.windowFunctionComboBox.addItem("")
        self.windowFunctionComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.windowFunctionComboBox)
        self.label_2 = QtWidgets.QLabel(QSpectrumAnalyzerSmoothingFrequency)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.windowLengthSpinBox = QtWidgets.QSpinBox(QSpectrumAnalyzerSmoothingFrequency)
        self.windowLengthSpinBox.setMinimum(3)
        self.windowLengthSpinBox.setMaximum(1001)
        self.windowLengthSpinBox.setProperty("value", 11)
        self.windowLengthSpinBox.setObjectName("windowLengthSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.windowLengthSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(QSpectrumAnalyzerSmoothingFrequency)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.windowFunctionComboBox)
        self.label_2.setBuddy(self.windowLengthSpinBox)

        self.retranslateUi(QSpectrumAnalyzerSmoothingFrequency)
        self.windowFunctionComboBox.setCurrentIndex(1)
        self.buttonBox.accepted.connect(QSpectrumAnalyzerSmoothingFrequency.accept) # type: ignore
        self.buttonBox.rejected.connect(QSpectrumAnalyzerSmoothingFrequency.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QSpectrumAnalyzerSmoothingFrequency)
        QSpectrumAnalyzerSmoothingFrequency.setTabOrder(self.windowFunctionComboBox, self.windowLengthSpinBox)
        QSpectrumAnalyzerSmoothingFrequency.setTabOrder(self.windowLengthSpinBox, self.buttonBox)

    def retranslateUi(self, QSpectrumAnalyzerSmoothingFrequency):
        _translate = QtCore.QCoreApplication.translate
        QSpectrumAnalyzerSmoothingFrequency.setWindowTitle(_translate("QSpectrumAnalyzerSmoothingFrequency", "Frequency Smoothing - QSpectrumAnalyzer"))
        self.label.setText(_translate("QSpectrumAnalyzerSmoothingFrequency", "&Window function:"))
        self.windowFunctionComboBox.setItemText(0, _translate("QSpectrumAnalyzerSmoothingFrequency", "rectangular"))
        self.windowFunctionComboBox.setItemText(1, _translate("QSpectrumAnalyzerSmoothingFrequency", "hanning"))
        self.windowFunctionComboBox.setItemText(2, _translate("QSpectrumAnalyzerSmoothingFrequency", "hamming"))
        self.windowFunctionComboBox.setItemText(3, _translate("QSpectrumAnalyzerSmoothingFrequency", "bartlett"))
        self.windowFunctionComboBox.setItemText(4, _translate("QSpectrumAnalyzerSmoothingFrequency", "blackman"))
        self.label_2.setText(_translate("QSpectrumAnalyzerSmoothingFrequency", "Window len&gth:"))
